export const FUGLE_MARKETDATA_REST_CLIENT = Symbol('FUGLE_MARKETDATA_REST_CLIENT');
export const FUGLE_MARKETDATA_WEBSOCKET_CLIENT = Symbol('FUGLE_MARKETDATA_WEBSOCKET_CLIENT');
export const FUGLE_MARKETDATA_CLIENT_OPTIONS = Symbol('FUGLE_MARKETDATA_CLIENT_OPTIONS');
